# Generated by Django 2.1.5 on 2019-02-24 00:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Title')),
                ('is_active', models.BooleanField(default=True)),
                ('creation_time', models.DateTimeField(default=datetime.date.today)),
                ('expiry_date', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100000)),
                ('answer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modification_time', models.DateTimeField(default=datetime.date.today)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dynamicforms.Forms')),
            ],
        ),
        migrations.AddField(
            model_name='datatable',
            name='form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dynamicforms.Forms'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dynamicforms.Questions'),
        ),
    ]
