# Generated by Django 2.1.7 on 2019-03-17 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicforms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatable',
            old_name='is_active',
            new_name='is_draft',
        ),
        migrations.AlterField(
            model_name='datatable',
            name='submitter_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
