# Generated by Django 2.1.4 on 2019-02-19 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190218_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatRoom',
        ),
        migrations.AddField(
            model_name='message',
            name='chatRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CharRoom_messages', to='chat.ChatRooms'),
        ),
    ]
