# Generated by Django 2.1.7 on 2019-03-16 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190226_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrooms',
            name='category',
            field=models.CharField(choices=[('G', 'Group Room'), ('P', 'Personal Room')], max_length=1),
        ),
        migrations.AlterField(
            model_name='chatrooms',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\d\\-_]*$', 'Only alphanumeric characters, _ and -  are allowed. No Space.')]),
        ),
    ]
