# Generated by Django 2.1.5 on 2019-03-08 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190226_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomaccess',
            options={'verbose_name_plural': 'Room Access'},
        ),
    ]
