# Generated by Django 2.1.4 on 2019-02-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190219_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrooms',
            name='display_line_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatrooms',
            name='display_line_2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
