# Generated by Django 2.1.4 on 2019-01-05 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('CreationTime', models.DateTimeField(auto_now=True)),
                ('ExpiryTime', models.DateTimeField()),
                ('IsActive', models.BooleanField(default=True)),
                ('HasAttachment', models.BooleanField(default=False)),
                ('Attachment_ID', models.IntegerField(default=0)),
                ('Creator_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
