# Generated by Django 2.1.5 on 2019-03-19 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_expired',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expiry Date'),
        ),
    ]
