# Generated by Django 2.1.5 on 2019-03-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachment',
        ),
        migrations.AddField(
            model_name='post',
            name='fileAttachment',
            field=models.FileField(blank=True, null=True, upload_to='announcements/files'),
        ),
        migrations.AddField(
            model_name='post',
            name='imageAttachment',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/images'),
        ),
    ]
