# Generated by Django 2.1.5 on 2019-03-08 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190308_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
