# Generated by Django 2.1.5 on 2019-03-08 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190308_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_expire',
        ),
    ]
