# Generated by Django 2.2.6 on 2019-11-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=14167362100, max_length=20),
            preserve_default=False,
        ),
    ]
