# Generated by Django 2.1.5 on 2019-01-18 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('percent_indigenous', models.FloatField()),
                ('percent_gdp_on_ed', models.FloatField()),
                ('definition', models.CharField(max_length=50)),
                ('average_education', models.CharField(max_length=50)),
                ('strategy', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('met', models.BooleanField(default=False)),
                ('moc', models.BooleanField(default=False)),
                ('ethics', models.BooleanField(default=False)),
                ('status_request', models.BooleanField(default=False)),
                ('ri_1_tools', models.DateTimeField(default=django.utils.timezone.now)),
                ('general', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('is_private', models.BooleanField(default=False)),
                ('type_of_inst', models.CharField(max_length=150)),
                ('student_count', models.IntegerField()),
                ('staff_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInstituteContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=150, null=True)),
                ('degree', models.CharField(max_length=150, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
        ),
    ]
