# Generated by Django 2.1.5 on 2019-03-19 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchinstitutecontact',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.City'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.Country'),
        ),
    ]
