# Generated by Django 2.1.5 on 2019-03-07 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20190225_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='other_staff_count',
        ),
        migrations.AddField(
            model_name='institution',
            name='abbreviation',
            field=models.CharField(default='YU', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='average_education',
            field=models.CharField(max_length=50, verbose_name='Average level of education'),
        ),
        migrations.AlterField(
            model_name='country',
            name='percent_gdp_on_ed',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage of GDP spent on education'),
        ),
        migrations.AlterField(
            model_name='country',
            name='percent_indigenous',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage of indigenous population'),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Average age'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='ethics',
            field=models.BooleanField(default=False, verbose_name='Ethics approved'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='focus_pst',
            field=models.CharField(blank=True, default='Not yet defined', max_length=50, null=True, verbose_name='Focus on K/P/S/T'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='further',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Further levels of education'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private research institution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='moc',
            field=models.BooleanField(default=False, verbose_name='Memorandum of cooperation'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name of institution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='online',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Use of online learning material'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='percent_indigenous',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage of indigenous students'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type_of_inst',
            field=models.CharField(max_length=50, verbose_name='Type'),
        ),
    ]
