# Generated by Django 2.1.5 on 2019-02-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_auto_20190225_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='ri_1_tools',
            field=models.DateField(),
        ),
    ]
