# Generated by Django 2.1.5 on 2019-04-26 01:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('population', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('percent_indigenous', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage of indigenous population')),
                ('percent_gdp_on_ed', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage of GDP spent on education')),
                ('definition', models.CharField(max_length=50)),
                ('average_education', models.CharField(max_length=50, verbose_name='Average level of education')),
                ('strategy', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of institution')),
                ('abbreviation', models.CharField(max_length=15)),
                ('met', models.BooleanField(default=False)),
                ('moc', models.BooleanField(default=False, verbose_name='Memorandum of cooperation')),
                ('ethics', models.BooleanField(default=False, verbose_name='Ethics approved')),
                ('status_request', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False, verbose_name='Private research institution')),
                ('ri_1_tools', models.DateField()),
                ('general', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('type_of_inst', models.CharField(max_length=50, verbose_name='Type')),
                ('student_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('staff_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('internet_access', models.CharField(blank=True, max_length=50, null=True)),
                ('online', models.CharField(blank=True, max_length=50, null=True, verbose_name='Use of online learning material')),
                ('guest_lectures', models.CharField(blank=True, max_length=50, null=True)),
                ('environment', models.CharField(blank=True, max_length=50, null=True)),
                ('focus_pst', models.CharField(blank=True, default='Not yet defined', max_length=50, null=True, verbose_name='Focus on K/P/S/T')),
                ('further', models.CharField(blank=True, max_length=50, null=True, verbose_name='Further levels of education')),
                ('school_size', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('community_size', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('girl_ratio', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('qualifications', models.CharField(blank=True, max_length=50, null=True)),
                ('percent_indigenous', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage of indigenous students')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Average age')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInstituteContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=150, null=True)),
                ('degree', models.CharField(max_length=150, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'verbose_name_plural': 'Research Institution Contacts',
            },
        ),
    ]
